language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t joaoguilherme1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joaoguilherme1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: react-app
  env: react-app-env
  bucket: react-app-bucket
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY